env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - prettier
overrides: []
ignorePatterns:
  - "node_modules*/"
  - "e2e/"
  - "dist/"
parserOptions:
  ecmaVersion: "latest"
  sourceType: module
plugins:
  - react
rules:
  camelcase: 0
  consistent-return: 0
  import/prefer-default-export: 0
  jsx-a11y/label-has-associated-control: 0
  no-param-reassign: 0
  no-plusplus: 0
  no-restricted-syntax: 0
  no-underscore-dangle: 0
  no-unreachable: 1
  no-unused-vars: 1
  no-bitwise: 0
  quotes: [2, "double", { "avoidEscape": true, "allowTemplateLiterals": true }]
  react/jsx-filename-extension: 0
  react/jsx-no-constructed-context-values: 0
  react/jsx-props-no-spreading: 0
  react/no-array-index-key: 0
  react/prop-types: 0
  react/react-in-jsx-scope: 0
