ARGUMENT_NOISE = [
    "Here are my reasons:",
    "Wow.",
    "I've always sided with you but had absolutely no idea how to word it.",
    "Well said.",
    "I know a lot of people don't care about it so much",
    "I think you're right.",
    "I agree.",
    "Sounds like your mind is made up, and rightfully so.",
    "I kind of messed up the writing in my last comment.",
    "I really don't think this is comparable.",
    "I don't really think so.",
    "I would argue you are focusing on the wrong issue.",
    "Without any sort of statistics there's no way you can know that for sure.",
    "Yup, I completely agree with you.",
    "I think that was his/her point",
    'Almost assuredly "asocial."',
    "Asocial, you're right.",
    "I mean..",
    "That's a personal subjective thing about you, and I don't the first thing about you",
    "so I agree.",
    "In what way do you consider it bad ?",
    "I agree.",
    "Admittedly, this is all anecdotal.",
    "Or at least to me.",
    "Maybe that makes a difference.",
    "I also don't think people realise how much it affects them.",
    "You know, I think I'm inclined to agree with them.",
    "No I think you're right.",
    "Ouch.",
    "Nice.",
    "Please excuse my approximate english.",
    "But even, Not so much.",
    "Well.",
    "Edit : All that being said.",
    "Actually, not really.",
    "but I doubt that is the case for many",
    "I won't argue because I believe you're right.",
    "So I agree with everything you say.",
    "Can you give an example where you thought it was?",
    "You make great points and I agree with all of them but there is one reason I think your overall argument is wrong.",
    "Maybe I can change your view on that part of it at least.",
    "Thank you everyone for your inputs.",
    "I have awarded deltas to the versions of these arguments that I found most compelling.",
    "This guy gets it.",
    "This.",
    "Thank you.",
    "Thank you for this.",
    "Thank you for the correction.",
    "I like this response.",
    "I appreciated this response.",
    "Thanks for the delta!",
    "I found this response convincing.",
    "Etc",
    "( see my comment to a breakdown )",
    "I found this response unconvincing.",
    "That's what I did.",
    "That's exactly what I did.",
    "Don't regret it.",
    "Do what feels right to you.",
    "Second best way, then.",
    "Those are my two options.",
    "Those are the two options.",
    "Sometimes, you have to play the long game.",
    "The truth is though, I would never do that.",
    "Since no one else is actually attacking your reasoning, I'll give it a go.",
    "In the end all you have is a bunch of misquoted, out of context, biased, and frankly intentionally misleading jargon that has no basis in reality.",
    "You make an excellent point here.",
    "And given what I listed out above, I still don't think you are on the right side of this.",
    "I'm not trying to convince you that you have to agree with me.",
    "This is sane reasoning, but not logical.",
    'And based on the fact that OP put "insane" in quotation marks, I\'m pretty sure they mean "illogical" or "dumb".',
    "If what OP meant was \"dumb\" then I wouldn't have even bothered posting in this thread because there's no point trying to change someone's mind who thinks everyone who sees it differently is stupid.",
    'That\'s what pretty much every CMV boils down to - "I think X is dumb, convince me otherwise".',
    "Well, my friend, I certainly disagree with you that that's what CMVs boil down to.",
    "The whole point of this forum is that you have an idea that you think could be wrong, and you are asking the other Redditors - who presumably are of roughly equal intelligence - to help you hash it out by presenting arguments against it.",
    'Man, a forum that was just dedicated to "I am much smarter than you."',
    "This is what I think.",
    "I agree with you, and think it's shitty, but I still stand by my initial comment.",
    "Being pedantic and taking everything exactly literally are poor arguments that don't lead anywhere.",
    "If you disagree, either ask questions to clarify or argue against the idea, but mincing words gets everyone nowhere.",
    "To me that suggests they don't fully understand the implications of what they're arguing.",
    "I wasn't just being pedantic, I was hoping that pointing out their mistake would cause them to reconsider the underlying logic, which IMO is tenuous at best.",
    "People aren't idiots.",
    "Don't we agree?",
    "I just don't get this argument.",
    "You are putting up a straw man.",
    "Here are arguments against your arguments:",
    "You're just being obtuse.",
    "If you need to redefine commonly understood words you don't have an argument.",
    "WTF seriously?",
    "This is true.",
    "That is a definite fact.",
    "And that's not cool.",
    "What?",
    "Edit -",
    "Well that's a positive.",
    "Ok, that's great",
    "Actually:",
    "And that's something.",
    "Yeah.",
    "What?",
    "Also.",
    "That's the thing.",
    "I think that says a lot.",
    "Ugh.",
    "Absolutely agree.",
    "yeah",
    "Ha.",
    "Too vague.",
    "Be more specific.",
    "How?",
    "What?",
    "Seriously?",
    "Clearly.",
    "Out",
    "and that's it.",
    "And?",
    "I'm done.",
    "Tip.",
    "Hint.",
    "Wow.",
    "Link?",
    "Ok.",
    "Such clarity.",
    "Seems legit.",
    "At all.",
    "Nope.",
    "Irrelevant.",
    "No.",
    "Nope.",
    "It might be me that did that, and if so I apologize.",
    "I guess my wording could have been better.",
    "This comment has been removed per rule 2:",
    "Sorry about that",
    "Its okay",
    "This comment has been removed per rule 2:",
    "You completely lost it in the first sentence.",
    "I see you really did a good job changing it...",
    "What are you even talking about?",
    "Who is saying that?",
    'Tons of idiots online said "oh yea, sure" and disregarded it.',
    "Like who?",
    "Many of my coworkers and excoworkers for starters.",
    "It likely never even occurred to them, because they are not stupid.",
    "But they are not ignored.",
    "I care what they did.",
    "Everyone.",
    "People have criticized it for as long as I can remember.",
    "What the fuck who even cares.",
    "I suspect most of them are too young to remember.",
    "Just because you don't like it doesn't mean others didn't.",
    "You assume people aren't talking about this?",
    "But they don't actually care.",
    "Do they?",
    "So who has done this?",
    "Those are totally influence free.",
    "Thanks for listening to my rambling",
    "and I hope to have a good discussion with some of you!",
    "Thank you to everyone who contributed to this discussion.",
    "Hey, not to bug you, but I'd appreciate editing in the delta when you get a chance.",
    "I know the thread kinda blew up on you.",
    "I am still trying to read through all of these comments and I plan to hand out deltas and edit my original post with my thoughts, when I've sufficiently gathered them...",
    "This thread blew up, so I'm a little reluctant to add anything out of feeling like I'm pissing into a wind -- one that's already sorta blowing in my direction anyways.",
    "You're welcome, rest of the world.",
    "Thank you for the insight into why you believe what you do! :)",
    "Thank you for the input!",
    "Great, thoughtful post indeed.",
    "Thanks for taking the time to type it all out!",
    "Thank you for this explanation.",
    "If I were the OP, I would delta this post.",
    "Deltabot is having some issues at the moment.",
    "Responding to this comment will cause me to recheck your delta comment.",
    "Thank you for elaborating :)",
    "Thanks for this viewpoint.",
    "Thanks for taking the time to read it!",
    'Thanks for being conducive to conversation. /s"',
    "Why?",
    "Why not?",
    "Why is that?",
    "Do you have the link for that?",
    "(I need to review the rule where I am, I'm just speculating)",
    "You posted two links.",
    "My link contained a source to the actual study, sorry it stopped working.",
    "Anyway... try google.",
    "Opposing other peoples (sourced) facts with nothing in support of your argument is lazy.",
    "My argument is one of common sense, not research.",
    "Your specific scenario does not invalidate my argument.",
    "But you, like most of the replies I'm getting, are ignoring the crux of my argument.",
    "Theoretically, I agree with you.",
    'I can\'t be "wrong in your thinking" in a hypothetical situation.',
    "and I think my argument stands.",
    "It's not your place to say whether I should be okay with that fine.",
    "My comment applies more to, if there is room to move over, you should.",
    "You can't have it both ways.",
    "If it is convenient for me to get over, I will when the time is right.",
    "If I feel like it is a good time to move over, I will.",
    "Their choices are on them.",
    "You should move over as soon as safely possible.",
    "You should.",
    "I chose the second option.",
    "I'll give you a !delta for this.",
    "Confirmed: 1 delta awarded to /u/Salanmander (6).",
    "Confirmed: 1 delta awarded to /u/Leumashy (4).",
    "Delta System Explained | Deltaboards",
    "What?",
    "Why?",
    "Why not?",
    "Note: Your thread has not been removed.",
    "Your post's topic seems to be fairly common on this subreddit.",
    "Similar posts can be found through our wiki page or via the search function.",
    "Please contact the moderators of this subreddit if you have any questions or concerns.",
    "EDIT:",
    "No, that would be ridiculous.",
    "No.",
    "So...",
    "And yes.",
    "Sure.",
    "Exactly.",
    "I would certainly say so.",
    "Agreed.",
    "Yes, I do.",
    "I don't think so.",
    "The fact they're unpopular doesn't make them special in that regards.",
    "Apparently it does though.",
    "Now, show me anyone doing that.",
    "Who makes that call?",
    "No one likes being confronted with ideas that are grotesque to them, but its a fact of life.",
    "Not just because I don't like it.",
    "I think the sentiment turns on you, though, because you're relying on the outlandishness of their opinion to deny them the space to voice that opinion.",
    "Some do, some don't.",
    "Go for it).",
    "Other results",
    "[Wiki][Code][Subreddit]",
    "From ",
    "More at",
    "One of the links has a study that concludes:",
    "Any citations?",
    "Your post's topic seems to be fairly common on this subreddit.",
    "Similar posts can be found through our wiki page or via the search function.",
    "Please contact the moderators of this subreddit if you have any questions or concerns.",
    "Before I respond to anything else, what is you article about?",
    "[Wiki][Code][Subreddit]",
    "Note: your thread has not been removed.",
    "I am a bot, and this action was performed automatically.",
    "This delta is currently disallowed as your comment contains either no or little text (comment rule 4).",
    "If you edit this in, replying to my comment will make me rescan yours.",
    "Doesn't feel like I'm stretching things too far.",
    "Nobody comes on here to preach their (wrong/controversial) ideas.",
    "oh I didn't mean to imply that at all, I meant to fully articulate that position.",
    "edit:I meant the logical extrapolation of your position.",
    "I'll save it for later in the debate, when things are clearer.",
    "Also your basis for argument is not advisable.",
    "I think you've got it the wrong way around.",
    "Do you now see the flaws in your logic?",
    "You're misunderstanding.",
    "edit: re-reading, we definitely agree on the last two points.",
    "Rather, they just sound uneducated.",
    "But this situation only exists because both sides have picked ridiculous spin terms for their positions.",
    "My argument operates within the confines of this context.",
    "If you want to argue that it shouldn't be this way, that's a different argument.",
    "but just because it is easy doesn't mean it is right.",
    "I didn't say I don't have a problem.",
    "Try asking an apple whether it rather be an orange.",
    "Prooobbbbbably not the best idea...",
    "I didn't say the choice itself was morally ambiguous.",
    "I said you would prefer not to have to make that choice.",
    "I attempted to track down the actual data on which this claim was based, but failed.",
    "In every instance where I found someone who used the figures from your second link and then provided a citation, the citation was to another article offering the same assertion, and never to the actual source.",
    "Like your infographic, which contains superscript suggesting a citation I could check, but yet has no actual citations.",
    "This article in turn was NOT a study, but a (rather... fervent) op ed.",
    "But finally I found an actual reference to a study from which these error rate figures were obtained.",
    'Not a link, not a citation, just the statement that this claim came from a "criminologist" named "Kates."',
    "No actual citation was provided.",
    "In both cases no actual citation was provided.",
    "And finding it appears to be beyond my ability.",
    "Does the graphic have a source?",
    "Sure to find unbiased analysis over there...",
    "Here's the study OP was likely referring to.",
    "Page 41.",
    "I have interest in data relevant to the issue.",
    "My mind is open, but I do need information that is actually related to the matter we are discussing, not just something that isn't actually related, but sounds like it is....",
    "basic infographic on it",
    "None of your links are useful.",
    "The only one that approaches usefulness is the second, but it just repeats what you said, and provides a dead link in support.",
    "Fortunately a pdf mirror was provided.",
    "You may want to head over to /r/dgu.",
    "They've already been posted in this thread.",
    "That's pretty cynical.",
    "There are.",
    "This is just false.",
    "Perhaps you could help me figure out where I am falling short in my explanation?",
    "Is that statement false?",
    "OK, not to many people have focused on on your reasoning here",
    "I never asserted that.",
    "I just simply don't see any evidence whatsoever that could lead you to that conclusion.",
    "I therefore asked you the question about what evidence you had in the hopes that you would EITHER present some evidence that would lead to me learning something, OR realize that your view was based on no evidence whatsoever and therefore change it.",
    "It's the same concept.",
    "Don't discount provided evidence just because you disagree with the conclusion.",
    "I haven't discounted them, I am just stating that I am aware that they are only looking at one side of the issue.",
    "You are comparing apples to oranges.",
    "Do you have support for this assertion?",
    "please support this assertion.",
    "1 of them, I'm not sure about.",
    "Yes.",
    "I'm not sure...",
    "I looked it up.",
    "I'll wait.",
    "Let me guess...",
    "No.",
    "Isn't it?",
    "Very true.",
    "What are you talking about?",
    "Are you being serious?",
    "Nope.",
    "Hm, probably not.",
    "Yes, I am.",
    "I don't think so.",
    "Now I'm curious.",
    "Truth.",
    "Hmm.",
    "Hm.",
    "Interesting.",
    "Big.",
    "Very strange.",
    "I would agree with those things.",
    "I think I agree with these.",
    "But i have to agree with you.",
    "Generally I would agree with you.",
    "I disagree with you for two reason.",
    "I generally agree with the idea.",
    "I generally agree with you.",
    "I agree.",
    "Yeah, but it takes a little bit of knowledge of the subject to realize that the guy didn't probably didn't have his facts right.",
    "Also, downvotes don't magically turn facts false, so you all can just quit that shit.",
    "That's a poor analogy.",
    "I think we're gonna see a lot of poor analogies.",
    "The problem I have with your argument is that I feel like the logic is flawed.",
    "I'd started believing OP, but I cannot find a flaw in your logic.",
    "I wasn't sure which side of the argument made more sense until i read yours.",
    "This is a super interesting argument.",
    "Those are extreme examples, but it is the same principle.",
    "But istead of telling me that, you start insulting me.",
    "What's wrong about this?",
    "I also have an argument that probably won't CYV, but for me it's what matters most.",
    "I'll give an example.",
    "Is this unconditional?",
    "I'll try to reword it, but it may end up just being redundant..",
    "So, sorry again, what I typed sounds complicated to me.",
    "If a part of my post seems nonsensical, it's most likely because I forgot to rewrite a part of my notes, or I made a typing mistake.",
    "I suppose it could have been clearer, though.",
    "Again, this is my first post to /r/changemyview, so sorry if I'm not being.. as clear and concise as is normal on this subreddit, but I am having a lot of trouble with this.",
    "I am using a lot of rhetorical questions, and my typing/ language may appear...",
    "That's why so many of the questions seem rhetorical.",
    "It's because I am asking myself these questions.",
    "Also, to explain my use of the ellipses.",
    "I use ellipses mostly when I am trying to think of a way to say something, or I'm trying to think of a word, and I just can't.",
    "The ellipses are, in writing, my way of showing hesitation in the words I am using after the ellipses.",
    "It's a way of showing that I am using those words in substitution of a thought that I can't properly type because I... am dumb.",
    "Thank you all for the responses so far.",
    "I do wish to have as many responses as possible, but I am going to sleep right now.",
    "I am typing my thoughts back to you.",
    "Even if I do not reach anything conclusive, I again want to say thank you to everyone who is posting for at least giving me a new perspective, or clarification.",
    "As per the sidebar, comments supporting OP original idea must be restricted to replies in comments and my support for not changing your view was relevant here.",
    "And that distinction is why the two of you disagree fundamentally.",
    "Is my position unusual?",
    "No, your analogy is nonsense.",
    "So you pick which premise you have a gripe with, or how the premises lead to the conclusion, and we can productively discuss it.",
    "It is like in the discussion of aesthetics, it is hard to get into discussions like 'what makes good art?' when you are bogged down in the question 'what is art?', so for discussions sake they use placeholder definitions.",
    "Of course they are exclusive, but I felt as if you were focusing on the former, when that wasnt the point.",
    "You seem to have a consistent position AFAICT, even though I find it an odd one.",
    "You must have some logic underlying this claim.",
    "Or, you know, ignore the main point, whatever, you do you.",
    "Considering his username he may simply have been trying to fit your argument and his name in the same discussion.",
    "If not, how are you disagreeing with my premise?",
    "I am not sure which part of this is supposed to change my view.",
    "I don't see what about this is supposed to change my view.",
    "Is telling me my view is irrelevant supposed to change my view?",
    "I am unsure what part of this is supposed to change my view.",
    "I am unclear what you mean, and unclear as to why it is relevant.",
    "I am unsure which part of this is supposed to change my view.",
    "I'll take a stab at it, and you can tell me what I got wrong.",
    "What part of my post are you disagreeing with?",
    "I understand.",
    "I get what you're trying to say.",
    "Well, good for you.",
    "That's cute.",
    "I know.",
    "For you.",
    "I understand.",
    "Sorry about that, my bad.",
    "I understand.",
    "That's fine if it is.",
    "My apologies, then.",
    "That's fine.",
    "Really?",
    "Watch:",
    "What?",
    "Really?",
    "Also, seriously?",
    "So wait.",
    "oh well?",
    "Oh come on.",
    "Ehh.",
    "Boo hoo.",
    "Meh.",
    "Lol.",
    "Uhuh.",
    "Oh my god.",
    "Oh man, we are so done.",
    "Lol.",
    "Meh.",
    "Oh please.",
    "Here's the fundamental problem as I see it.",
    "So how do we fix this?",
    "Even if it's not all that common, I don't think we should ignore the problem.",
    "That's just being emotional.",
    "Is it solely emotion though?",
    "If we just look at it purely rationally, enacting more resolutions to prevent this for very little drawback seems like a win.",
    "Because he is not the one that is problematic.",
    "There is no positive outcome here.",
    "You make the problem worse.",
    "More often than not things are made worse.",
    "You've got some major problems if that seems like a solution.",
    "We should fix it.",
    "There's no room for emotion here.",
    "That's not a systematic problem, that's a one-off.",
    "Emotional, irrational decision making.",
    "It is not worth it to me.",
    "No, I don't think you should.",
    "I think that was the right thing to do.",
    "If it's not enough, you lose.",
    "What makes you think I, personally, get any advantage out of this?",
    "Because you have a stake in these outcomes?",
    "Don't expect me to join you.",
    "Why do you think this works in your favor?",
    "I'll just move.",
    "It's your choice to make.",
    "I do not think it is worth it.",
    "I'm not taking that tradeoff.",
    "I have a sufficiently large advantage to give him a chance.",
    "Almost nothing is worth that.",
    "I don't know if this is a personal issue for you.",
    "Which would you choose?",
    "Brilliant plan.",
    "Not worth worrying about.",
    "I don't think so.",
    "Maybe.",
    "No.",
    "Just, no.",
    "Far from it.",
    "Not really, no.",
    "And I;m having a hard time finding anything.",
    "There are a million studies, going over a million different things, and coming to a million different conclusions, which may or may not correlate to each other.",
    "For every study you find saying one thing, I can find one to say the opposite.",
    "I'd ask you to cite a source.",
    "Where the heck are you pulling that from?",
    "The stats are persuasive, but it is important to keep in mind the broader picture.",
    "And very little drawback seems like a simplified perspective.",
    "In my head, it's pretty nice.",
    "But nothing's ever simple.",
    "It's never pretty.",
    "I've never said it would be pretty.",
    "Life is totally awesome right now!",
    "But I would maintain that nine times out of ten that feeling is purely illusionary.",
    "I never said it would be easy, or desirable.",
    "It doesn't look so great.",
    "Nothing's ever simple",
    "I beg you to do so.",
    "I gave it a shot.",
    "Just be sure to plug it in when you're done.",
    "See that's what I'm talking about.",
    "Yeah but you're not a qualified expert in the field so we should be cautious with your premises.",
    "Do you have any evidence for that?",
    "That simply is not true.",
    "If you would recant, then you're essentially stating your feeling about a matter that is empirical, and we just haven't done the work to figure out yet.",
    "I had forgotten to add that part.",
    "I missed your edit about public funds.",
    "I was corrected below.",
    "I had forgotten to include that part.",
    "Ah, missed the edit.",
    "My mistake.",
    "Sorry, I got kinda grammatically confused there.",
    "Nope, not at all.",
    "yeah",
    "Perhaps.",
    "Sadly, no.",
    "Bullshit",
    "No.",
    "I say no.",
    "Well that's a different story.",
    "Agreed.",
    "and you think.",
    "Go work for The Nation, or start a think tank and create a publication of your own.",
    "Take this from a 2005 study.",
    'The thing missing from your statistical analysis is the phrase "consistently over all available measurements".',
    "Here are several academic papers supporting this claim (and I'm sure you could find more):",
    "If you can summarize the context of those articles it would be appreciated.",
    "Reading the abstracts for those results will give you a good summary of the papers' conclusions.",
    "That's a stretch of correlation if I may say so.",
    "I tried to search as well and couldn't find the data either.",
    "Where did you get that from?",
    "I am not aware of such research, but if it's there I'd recommend just listening to the people that know.",
    "I suppose I'm not really sure what it is you want here.",
    "I think if we slightly rephrase the question this way, we could have a much more valuable conversation without getting caught up in this gotcha game people are trying to play with your original phrasing.",
    "I'm not really sure what you are getting at.",
    "That's not the answer, that's the beginning of the question.",
    "You have to understand that:",
    "I agree, maybe I wasn't clear with what I was asking for.",
    "Anyway its late and my brain can only do so much at this hour.",
    "Do you think they need to spend time also talking about other factors for some reason?",
    "Should someone have to mention every single factor every time they want to discuss one of the factors?",
    "As long as you acknowledge there are other factors, you can choose to discuss one of the factors.",
    "If you choose to discuss one of the factors as if it is the only factor then you are being dishonest.",
    "To me it's dishonest to do this without looking at other factors.",
    "There are usually tons of factors.",
    "But then you have to consider these factors:",
    "There are always a million factors and variables.",
    "I don't say that it needs to not be taken into consideration, but I think other factors need to be taken into consideration as well.",
    "We are ignoring that their are other factors, and to me that's being dishonest.",
    "I'm not saying those other factors should be ignored or disregarded.",
    "This was an unimpressive CMV if your views can be changed by unsupported thoughts.",
    "Used to feel more or less the same way you did until this essay changed my mind-",
    "This is the response that should have changed the OP's mind.",
    "1) Why do you hold your view?",
    "Answer me these questions:",
    "Agreed.",
    "Agreed 100%.",
    "So we agree on many fundamental points.",
    "Do you agree?",
    "We're in agreement here.",
    "Which I personally agree with but you may not.",
    "Good point.",
    "Very good point.",
    "That goes to prove the point.",
    "So.",
    "mmmm.",
    "OP.",
    "Damn.",
    "Think that through though.",
    "Nice.",
    "Nice!",
    "Used.",
    "To.",
    "Haha.",
    "How fascinating.",
    "... And there it goes.",
    "Gone.",
    "Gone.",
    "Natural.",
    "Sorry ryeander, your post has been removed:",
    "Kurtze, your post has been removed:",
    "Sorry txBuilder, your post has been removed:",
    "Your submission has been automatically removed because it is too short (Rule A).",
    "Be sure your post also follows the other submission rules, or your submission may be automatically removed again.",
    "I am a bot, and this action was performed automatically.",
    "Well his argument is predicated as such:",
    "Lets have a better, more realistic example.",
    "That's not true at all.",
    "You failed to challenge his view.",
    "Your own argument, taken to its conclusion, will imply you are wrong.",
    "Yeah I was more presenting an argument for and against the OP.",
    "Surely you would have to prove this?",
    "Because that is, in essence, the same act.",
    "I'm sure you're synthesizing new information and reevaluating your assumptions, then.",
    "With a bit of digging I could provide a list of people who are in the highest echelons of business, medicine, law, academia which would disprove this, but you have illustrated that you are intelligent so such a list would be unnecessary.",
    "You're missing my point.",
    "Sorry for the long comment",
    "Yeah that's mostly fair, this has been most illuminating thank you.",
    "First CMV I've replied to, sorry for the terribly long post.",
    "This is another topic altogether, but to sum it up, I'll say this.",
    "Spent enough hours typing this up, so I'll stop here.",
    "Sorry for venturing off topic, I only hope that this doesn't fall on deaf ears considering how long it took to type.",
    "But it can do a very good job when used well.",
    "This wouldn't go over too well.",
    "I think that's something you might personally disagree with, something you might think shouldn't exist or isn't important to a degree.",
    "This isn't always a good thing.",
    "Basically, you're pointing out an obstacle to such a change.",
    "It's an important one that would need to be overcome, but it's not one that, at the end of the day, actually provides a valid reason why this shouldn't be done.",
    "Damn right it's an obstacle.",
    "Again, let's overcome the obstacle, and then revisit the sweeping change issue.",
    "What I'm saying is that your problem is not nearly widespread enough to matter in the scheme of things in comparison to the much larger issues that need to be addressed.",
    "So yes, it is something that needs to be addressed, but it's not a big enough obstacle to stand in the way of much more important changes.",
    "And how would that help?",
    "Hence a problem.",
    "but nonetheless it works.",
    "And that would be pretty hard to justify.",
    "That doesn't accomplish anything.",
    "I could see that being an issue.",
    "That's a great point.",
    "I hadn't considered it, but you're right.",
    "That's the real reason.",
    "That's part of it.",
    "I disagree with you.",
    "I'm not the only one with this opinion according to my source.)",
    "I don't agree with OP.",
    "I don't disagree in principle.",
    "I disagree.",
    "That's a really interesting thought.",
    "Simple as that.",
    "Good point",
    "Hi, that is very interesting question here!",
    "But, that's obviously not true for two reasons.",
    "This was true for a very long time, with recent history being the exception to the rule.",
    "Something about that statement has to be false.",
    "Maybe that's true, but so what?",
    'By definition "not everything" includes both "almost nothing" and "almost everything".',
    "That's not necessarily true.",
    "But, I think even that is untrue.",
    "That is no longer the case.",
    "This is definitely true to an extent.",
    "Things going as you plan?",
    "Your sense of how the world should work?",
    'And to be fair, perhaps using the phrase "well known" was both vague and confusing.',
    "There is a whole huge argument about it constantly here.",
    "Most are not.",
    "Not very much these days.",
    "I don't think this view holds true nowadays.",
    "It's not 100% but a strong majority.",
    "Does it even matter who brought it up?",
    "Well nowadays, they don't.",
    "For them, it works.",
    "Some do.",
    "What makes you think they don't?",
    "*Edit Typo",
    "EDIT:",
    "Edit: formatting.",
    "Don't know why my list formatting is broken.",
    "Edit: forgot a word",
    "(edit - minor rephrasing)",
    "Edit: formating",
    "Well thank you for that, and for being sensible.",
    "Thanks for the active moderating!",
    "This was really insightful, thanks!",
    "Hahaha thank you very much.",
    "Thanks for sharing. :)",
    "So, thank you for being so honest about your superficial worldview.",
    "These are great comments.",
    "I've removed this branch of comments per Rule 2: \"Don't be rude or hostile to other users.\"",
    "If you wish to edit your comments for a more civil tone, go ahead and then message the mods so we can re-approve them.",
    "OP has a legitimate point.",
    "That's fucked up.",
    "Good point.",
    "This is an amazing point.",
    "Yes, that is true.",
    "Thats a fair point.",
    "This is true.",
    "That is a fact.",
    "Absence of evidence is not evidence of absence.",
    "so how can we be sure?",
    "I would argue against your claim that the process has been lax.",
    "It's impossible to prove a negative after all.",
    "I'm not asking that we base decisions on a lack of evidence.",
    "I'm asking that we not become lax because of a lack of evidence.",
    "The latter is unprovable as there are an arbitrarily large number of possibilities and there just isn't enough time left in the universe to go through each one.",
    "The former is objectively unproven at this point, so no one can show you that evidence today.",
    "We'll just have to wait for more evidence to come to light.",
    "It sounds as though, despite evidence to the contrary, you are waiting for different evidence to emerge.",
    'They range somewhere between "guilty" or "nearly impossible to prove guilty".',
    "Nothing you've said has disputed this.",
    "Try to find a link so we can check the facts of the case.",
    "Let's check the facts of the case.",
    "You need to check your facts.",
    "Still, there isn't any evidence of that.",
    "You know what else is possible?",
    "You can't compound something that doesn't exist.",
    "I don't really see what you are basing this on.",
    "no, becuase it doesn't make any sense.",
    "It just doesn't make sense.",
    "I don't see how this would follow at all.",
    "That doesn't make a lot of sense.",
    "I do not see a connection here.",
    "I don't know if that makes sense to anyone.",
    "I think it is a least disingenuous way to present it.",
    "Which makes no sense.",
    "lol I'm trying to be the cool guy OP, but it's getting repetitive.",
    "i don't speak it, motherfucker",
    "And replies like this are a bit dickish.",
    "A lot of other people are making similar points to me, and being more eloquent about it.",
    "I think a lot of people aren't, and I'm finding i'm repeating myself.",
    "First of all, that is condescending as all hell.",
    "So the comment seems even more out of place as I am implying that I have ratings and people have opinions about me.",
    "I agree with OP's points, but this is the only one where I feel I actually have some actual information.",
    "That is not even a little but what I would expect a guy like that to sound like.",
    "My original points essentially parrotted, I think that's a good thing.",
    "You may ask, what is the point of all this?",
    "Everything I have said above, was constructed based on a few paragraphs I have read about you.",
    "So, you still ask yourself, what is the point of all this?",
    "Confirmed: 1 delta awarded to /u/Git_Off_Me_Lawn.",
    "Confirmed: 1 delta awarded to /u/hacksoncode.",
    "edit: thank you /u/awwwww_snap for this:",
    "Confirmed: 1 delta awarded to /u/heelspider.",
    "I think you get the bingo prize!",
    "Confirmed: 1 delta awarded to /u/awwwww_snap.",
    "Confirmed: 1 delta awarded to /u/cdb03b.",
    "Confirmed: 1 delta awarded to /u/cpolito87.",
    "Confirmed: 1 delta awarded to /u/OFF_THE_DEEP_END.",
    "Confirmed: 1 delta awarded to /u/bam2_89.",
    "Confirmed: 1 delta awarded to /u/imagineALLthePeople.",
    "Confirmed: 1 delta awarded to /u/awwwww_snap.",
    "Git_Off_Me_Lawn's delta history | delta system explained",
    "hacksoncode's delta history | delta system explained",
    "In this case the upvote or gold can be used, however the delta is supposed to be reserved for when someone changes your opinion.",
    "heelspider's delta history | delta system explained",
    "awwwww_snap's delta history | delta system explained",
    "cdb03b's delta history | delta system explained",
    "cpolito87's delta history | delta system explained",
    "OFF_THE_DEEP_END's delta history | delta system explained",
    "bam2_89's delta history | delta system explained",
    "imagineALLthePeople's delta history | delta system explained",
    "Someone with so many deltas should know better.",
    "The first thing I did after seeing their comment was check the deltas.",
    "awwwww_snap's delta history | delta system explained",
    "The above poster getoffmelawn may deserve a Delta for doing just that.",
    'Even going so far as to call taking their opinion into consideration "quite ridiculous".',
    "Sometimes bluntness is the best way to go.",
    "If you assume OP's original position was presented in good faith (the whole point of this subreddit), you should display equal good faith in your response, not cast bait.",
    "I'm all for responding in kind to a blunt or belligerent argument, but this is mostly because, at the point it is clear the other person is no longer a good faith participant, it is personally satisfying to throw out some snappiness before abandoning ship.",
    "I could easily see how one might take offense/give up on trying to change their mind and just resort to the sarcastic vitriolic tone we see here",
    'Especially since the person I am responding to spent zero time discussing things in good faith, and went directly to "taking offense/giving up on trying to change their mind and just resorting to the sarcastic vitriolic tone we see here"',
    "He's still following all the rules of the subreddit and is within his rights to attempted to change OP's views by any means necessary.",
    "If OP said this to me in real life, I would probably respond akin to hq3473.",
    "OP needs a slap of reality and sarcasm is actually a useful tool",
    "OP saying this to you in real-life (for whatever reason) is inherently different than OP posing this question to this particular subreddit.",
    "The subreddit doesn't exist for OP to grandstand (they should be willing to change their mind), but on the other hand, it also doesn't exist so that you can \"slap doses of sarcastic reality\" on people who hold opinions you find obviously wrong or uninformed.",
    "If they came here in good faith, are willing to have their mind changed, and have an opinion that is obviously incorrect, then a short, equally good-faith response should suffice.",
    'Like, if someone wanders into subreddit X and creates a new post to ask some obvious, frequently asked, googleable question about X, then "google it or read the faq, you dummy" is an appropriate response.',
    'If they ask it in a "simple questions" thread though, then that is a completely unacceptable response.',
    "There are some people to be reasoned with and some people to be struck.",
    "hq3473 obviously thought OP fell into the latter and lacking the ability to physically strike them, resorted to their comment.",
    "And while it is snarky and tongue in cheek, imo the rule you referenced (Don't be rude or hostile to other users), specifically is designed to stop direct bickering at users about users.",
    "The comment here is more of a shot in the breeze commentary",
    "As for HQ### I'm not inclined to believe he /or",
    "but if he/or she did, I leave it to the mods to decide what to do with his/her comments.",
    "Speaking hypothetically, without pointing to any specific examples...",
    "I don't think you can make an absolute statement either way,",
    "I didn't mean it as an absolute.",
    "As I said, I don't think you can make an absolute statement either way.",
    "This is silly and pointless, because both statements can be true at the same time.",
    "I would be interested to see what examples others can come up with.",
    "Unfortunately, this is true on the internet.",
    "IRL however, this is not true at all.",
    "You can't be one without the other.",
    "That's simply objectively false.",
    "I would suggest googling wild claims before posting them.",
    "Thanks I'll check out Ariel Levy.",
    "Ok, here's a random statistic pulled off of google for you:",
    "That stat's fair game.",
    "I suggest just reading the subreddit for a while.",
    "not that I don't beleive you, i'd just love a source.",
    'Nothing dodgy about that piece of unconfirmed propaganda "science".',
    "Go to page 217, first paragraph on the on left, it lists a whole bunch of studies.",
    "besides which that paragraph is saying there are no other studies on this question.",
    "It's listing one or two near misses I guess.",
    "Have any been published in a real science journal?",
    "Peer reviewed?",
    "Or simply replicated by anyone?",
    'That sort of stuff is referenced nowhere in this "study" even though it has obvious comparisons.',
    "I mean set aside that the authors are 100% ideologically committed against the possible outcome of the survey, they have zero experience or knowledge of other people working in that field.",
    "So yeah, this study are not conducted by",
    "Also do you have any reason to question the legitimacy of the studies?",
    "You can see the list of people who cited it on the pages.",
    'Read the "Method" section',
    "Here is an overview.",
    "61 million hits.",
    "I don't think thats what he meant, as thats obviously ridiculous.",
    "This doesn't make any sense to me.",
    "This also doesn't make sense.",
    "I'm lost.",
    "I think I understand the what now.",
    "Does that make any sense to you?",
    "I'm a little confused.",
    "so I'm a little confused.",
    "What do you mean by this?",
    "I still don't understand.",
    "Come on, try to make sense here.",
    "Makes sense.",
    "I can't understand this comment.",
    "Does that make sense?",
    "That's confusing.",
    "Yeah, I still don't see how this makes sense.",
    "It doesn't make sense because he started from a fundamentally strange position.",
    "And that, is what I don't understand.",
    "that's ridiculous.",
    "oh jeez, well that's dumb.",
    "Come on, that doesn't seem reasonable.",
    "Correct reasoning.",
    "That can't be what you mean.",
    "I wouldn't say so.",
    "It's actually very common.",
    "I think that's improbable.",
    "There's a reason you should not be surprised, IMO.",
    "I'm a little surprised that you're surprised.",
    "I doubt that strongly.",
    "he's new....",
    "Just fucking no.",
    "Hard to say..",
    "I would love to provide it.",
    "Thanks for the links",
    "The movie version used to be on Netflix, not sure if it still is",
    "Source?",
    "link?",
    "I looked through those, and this is what I found:",
    "I didn't see these firsthand and only saw them linked from somewhere else a while back, but from March 23rd:",
    "Thank you for this, I need to take the time to parse through these and analyze their legitimacy.",
    "but I don't remember the name of it.",
    "Link us.",
    "So see this archive first.",
    "It's right there.",
    "Google image search can be scarily effective in some cases.",
    "I could be wrong on the specifics but I believe this is the gist(?).",
    "If you're referencing BlackVision (I think that was the name?)",
    "Here is an archive of the event you are referring to dude.",
    "Flipping though those, I found this:",
    "Check out this comment:",
    "I have seen this one, but that seems to be it.",
    "when?",
    "Any and all links get automatically deleted.",
    "Links were never allowed.",
    "Maybe you're in the wrong sub?",
    "I mean, read their shit.",
    "It is completely images or articles.",
    "And please don't try and use the slippery slope argument - that's a logical fallacy.",
    "It obviously is and even the decision makers on both side of the issue see it as such.",
    "Also to refute your point about the logical fallacy, that refers to a necessary cause-and-effect, but doesn't really apply to real-life slippery slopes which are certainly possible.",
    "I've seen the Slippery Slope Fallacy Fallacy all over the place lately.",
    "Not all slippery slope arguments are fallacies.",
    "Slippery slopes that are not slippery slope fallacies",
    "#2 is not actually a slippery slope argument in the first place, and therefore is not a slippery slope fallacy.",
    "But I've seen it get declared a slippery slope fallacy by people hoping to slap a big QED on the argument and score internet points.",
    "The slippery slope isn't necessarily a logical fallacy, situations can worsen or better in slow increments.",
    "It's a fallacy to claim slippery slope if you don't demonstrate or explain how it will occur.",
    "I generally agree with you but I'm concerned about the slippery slope.",
    "It is a pretty grey area however and it has a lot to do with specific circumstances of the case and the judge's leanings.",
    "Now, before pao and the new rules, cases exactly like this have happened in the past.",
    "I really don't like this analogy.",
    "It's a shit analogy.",
    "His analogy works perfectly.",
    "I'm not making an analogy.",
    "What part of what I wrote do you think was an attempted analogy?",
    "But even if you couldn't tell the difference instantly, with 5-10 minutes of training, it would STILL be a shit analogy, because you wouldnt need to dodge them anyway.",
    "I'm still talking about the analogy presented in OP's article.",
    "Let's use a different analogy.",
    "Well, no analogy is ever going to be perfect",
    "How does this work for an analogy OP?",
    "Sorry, check out my ninja edit for the rest of the analogy.",
    "I think this is exactly the analogy I needed to be able to identify what was wrong with the OP's analogy.",
    "Even better would be to use no analogy at all.",
    'Yeah, no analogy is perfect, which is why I ended with "or even better: no analogy at all[...]".',
    "That is a hyperbolic analogy, and very different from what this article, and my comment, describe.",
    "It's actually a pretty nonsensical analogy by any breakdown.",
    "The original point also can be compared with that metaphor.",
    "I'm not defending those analogies.",
    "I gave my own analogy.",
    "I included it in the analogies he gave.",
    "That's a bad analogy because (I think)",
    "I scrolled to the bottom of the page just to see if someone was stupid enough to use this horrible analogy that's been floating around on the blogosphere.",
    "That article has some pretty shitty writing, and overall the attitude does seem to be a little gung-ho.",
    "However, I think that focusing just on that aspect of the article, or the issue in general, is throwing the baby out with the bathwater.",
    "I read it.",
    "thank you for the article i am going to save it.",
    "I guess I can't really blame you, that blog lies itself with startling cheek:",
    "It's a lay summary.",
    "It's still a biased and shitty summary, particularly the end.",
    'The whole summary is rife with what wikipedia calls "weasel words", terminology and rhetoric designed to cause alarm and panic by making the results seem more significant than they really are.',
    "Let me start by thank you for having issue with the source article.",
    "At the top of the article is this nugget",
    "Tubmlr and blog posts aren't real life.",
    "Did you read the article?",
    "Specifically the opening paragraph?",
    "This article, I believe, is advocating the latter.",
    "However, unless the person in the book is suggesting some punitive measure of their own, I'll take it as a warning.",
    "The realities of my life are so vastly different from what this article talks about that it doesn't even seem worth getting angry about.",
    "The author obviously had no idea what he was talking about.",
    "I read them hastily on mobile.",
    "Or, tl;dr, people fucking suck.",
    "The only answer is to use common sense, and this is the core of the article is trying to get across in its warped, poorly-written way.",
    "While the article is written horribly and is unwittingly racist and sexist, this is essentially what it is trying to say.",
    "And following the logic in the article, as quoted here:",
    "I read that article, too, and found it pretty awful.",
    'It may not really be the "meat" of the article, but I think it\'s important.',
    "The flaw with this article is that the emotional message is disproportionate.",
    "that is written to be confrontational.",
    "It's what you'd call click-bait; sensational online tabloid \"journalism\".",
    "Written to cause strong emotional reactions and get people talking.",
    "While the article is pretty sub-par and hostile, they're not totally wrong.",
    "Sadly, the article seems to blow right past that, perhaps because of the target audience.",
    "I think the article is simply poorly written.",
    'Stick an "NSFW" warning on pics like those, if you can.',
    "Upvote the comments you agree with and think are the best.",
    "If everyone is upvoting it then it is clearly adding to the discussion, so other people will most likely reply with thoughtful responses.",
    "Should probably remove the downvote button then.",
    "1) Use Subreddit Stylesheet",
    "Also, people who whine about being downvoted are pussies.",
    "We have the voting buttons for a reason: so that stupid people don't show up at the top.",
    "I had no idea that the votes dictated placement in a thread, TIL.",
    "This knowledge makes the request to refrain from downvoting quite logical.",
    "I concur, if you don't like being downvoted conform your opinions or don't post.",
    'Well, by default, the comments are sorted by "new best."',
    "There's a little dropdown menu at the top of the section, where you can change it.",
    'No, by default the comments are sorted by "best".',
    "Downvoting is bad because it drowns out unpopular (on reddit) opinions.",
    "Well, the thing is, the logic behind downvotes is you downvote things that you think either:",
    "Also, I think that the upvotes/downvotes are a great system for gauging the opinion of the hive.",
    "If everybody downvoted that opinion, then there would only be people agreeing with OP.",
    "Reddit doesn't provide that ability.",
    "We've tried it with CSS, but it doesn't really work because there's so many ways to circumvent it and downvote anyway.",
    "If you browse on mobile or turn off the stylesheet, you can still downvote on those subs.",
    "It still would remove a majority of downvotes.",
    "All you need to do is turn of subreddit styles",
    "True, it would certainly discourage downvoting, even though it obviously wouldn't be 100 percent effective",
    "Asking me to not downvote stupidity will never work.",
    "Although he hasn't specifically stated it above, I'm sure that /u/cwenham ham isn't attempting to discourage downvoting of \"stupid\" comments that don't contribute to the discussion, just those that we disagree with.",
    'We do discourage "low effort" comments, such as jokes, written upvotes, "FTFY", image links with no other commentary, etc.',
    "We have used CSS to disable the downvote button on submissions, but it's not very effective.",
    "You could use the mobile interface, or disable subreddit styles, or use RES and press 'Z'.",
    "That's a wildly different concept.",
    "Your comparing apples to oranges.",
    "How are they equivalent?",
    "No, they are not the same.",
    "Apples and oranges man.",
    "You literally have no frame of reference to compare.",
    "Your comparison is idiotic, at best.",
    "That's not a good comparison at all.",
    "There is a huge difference there.",
    "Where is the difference?",
    "There is a difference.",
    "Saying they aren't comparable or absurdly different is disingenuous, but saying they are exactly the same isn't strictly true.",
    "What makes this different?",
    "That's the big difference.",
    "Better, maybe, but still not a very good comparison.",
    "Most unscientific tales from people who've lived on both sides of the fence say there's a very noticeable difference.",
    "So what's the difference?",
    "In degree, as far as I can see, and little else.",
    "Compared to what?",
    "See the difference?",
    "This is literally no different.",
    "I changed my view, Thanks everyone.",
    "Try and change my view.",
    "For your info, I actually changed my view.",
    "Came in leaning towards OP's view myself but you turned me right around.",
    "So, case closed means I changed your view?",
    "If this changes the view of my post, please elaborate again.",
    "It's all about perspective, and it may be time to change yours, or at least squint a little.",
    "Do you think your view would be changed provided one exception?",
    "IF I change my view I expect it to be a hit in the heart and not in the head.",
    "but I'm not sure what you are implying, what you want eleborated or clarified and would hope you could make things more compact.",
    "Don't be scared of me not understanding, if I don't I will let you know.",
    "To further elaborate on your responce:",
    "Let me rephrase it.",
    "To elaborate:",
    "This is kind of a confusing post, so my response might be similarly confusing.",
    "i think there should be clarifications.",
    "Could you elaborate this?",
    "Could you eleborate?",
    "Please let me clarify what I mean and I hope to hear a response from you based on that.",
]
