kind: PersistentVolumeClaim

apiVersion: v1

metadata:
  name: frame-explorer-mongodb-data
  labels:
    app: frame-explorer
    tier: mongodb

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-rbd
