version: "3"

services:
  api:
    image: api:latest
    build: api/
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./api:/app
      - api_root_data:/root
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - MONGODB_URL=mongodb://mongodb:27017
      - DEVELOP=true
    depends_on:
      - mongodb
    command: ./boot.sh

  frontend:
    image: node:20-slim
    working_dir: /app
    stdin_open: true
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend/:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_PORT=5000
    command: bash -c "chown -R node:node /app/node_modules && npm install && npm start"

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  api_root_data:
  frontend_node_modules:
  mongodb_data:
